name: Generate JSDoc

on:
  pull_request:
    branches:
      - main
      - PurichV-JSDocs
permissions:
        contents: write
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: JSDoc Generation # Generate the docs for JS info
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./docs
          config_file: jsdocs.json
          front_page: README.md
      - name: Commit JSDoc
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet || (git add . && git commit -m "Documentation Generated")
          git push