name: Generate JSDoc

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./docs

      - name: Commit JSDOCS
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated JSDocs"
          add: "./docs"
          author_name: github-actions
          author_email: github-actions@github.com

      - name: Push changes
        run: |
          git checkout -b jsdocs-update
          git push --set-upstream origin jsdocs-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update JSDocs"
          branch: jsdocs-update
          base: main
          title: "Update JSDocs"
          body: "This PR updates the JSDocs."
