name: GitHub pages

on: push

jobs:
  deploy:
    runs-on: [windows-latest,macos-latest,ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: andstor/jsdoc-action@v1.2.1
        with:
          source_dir: ./src
          recurse: true
          output_dir: ./out

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #     publish_dir: ./out
